# Generated by Django 5.1.6 on 2025-03-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userquizhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizhistory',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
