# Generated by Django 5.1.6 on 2025-03-22 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_userquizhistory_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 22, 19, 51, 54, 788291, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
